name: release

on:
  release:
    types: [created]
    branches: [ "main" ]
  push:
    tags:
      - *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven

      - id: install-secret-key
        name: Install gpg secret key
        run: |
          # Install gpg secret key
          cat <(echo -e "${GPG_KEY}") | gpg --batch --import
          # Verify gpg secret key
          gpg --list-secret-keys --keyid-format LONG
        env:
          GPG_KEY: ${{ secrets.AMIKOS_OSS_GPG_SECRET_KEY }}
      - name: Version bump
        run: |
          mvn \
                --no-transfer-progress \
                --batch-mode \
                -Dgpg.skip=true \
                -DskipTests \
                versions:set \
                -DnewVersion=${{  github.ref_name }}
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b ${{  github.ref_name }}
          git add pom.xml
          git commit -m "Increment version to ${{  github.ref_name }}" -a
          git push origin ${{  github.ref_name }}
      - name: Publish package
        run: |
          mvn \
                --no-transfer-progress \
                --batch-mode \
                -Dgpg.passphrase=${GPG_PASSPHRASE} \
                -DskipTests \
                clean package deploy
        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.AMIKOS_OSS_GPG_SECRET_KEY_PASSWORD }}
